# Environment
os: osx

install:
  - brew install hugo
  - sudo easy_install Pygments

# # Install the apt prerequisites
# addons:
#   apt:
#     packages:
#       - python-pygments

# Compile the site
script:
  - hugo
  - npm install -g gh-pages
  - gh-pages --dist public --dest docs/encompass --repo https://x-access-token:${GITHUB_TOKEN}@github.com/MoonsideGames/moonsidegames.github.io.git --branch master
