baseURL = "/"
publishDir = "public/docs/encompass"
languageCode = "en-US"
title = "Encompass Docs"
theme = ["hugo-notice", "hugo-theme-learn"]

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
  themeVariant = "encompass"
  description = "Documentation for Encompass ECS"
  author = "Evan Hemsley"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
